### ISSUE TITLE
ILiADS to-do list

### ISSUE THREAD

**Issue by andiesilva** [andiesilva/digitalderricke#6]
# Oxford TCP

- [x]  resolve remaining gaps 

- [x] verify page breaks sit outside of divs containing content - the page breaks before the content begins

- [ ] go through XML structure and identify all elements in use

- [ ] modernize u, i, vv spellings (silent)

- [ ] add persNames and rs (reference strings) with `@ref` attribute and the attribute value equal to person's xml:id

- [ ] add new people to prosopography file (not back!)

- [ ] make choice markup for at least first few pages

- [ ] change `@place` attribute value on the marginalia `<note>` elements from "margin" to "left-margin" or "right-margin"

# TEI Header

- [ ] idiosyncratic capitalization normalized - silent and same as TCP (plates and text)

- [ ] correction of u, i, vv - silent and counter to TCP (plates and text)

- [ ] remove end of line and un-hyphen end of line word breaks - silent and counter to TCP 

- [ ] choice markup of original early modern English to regularized modern English favoring modern British spelling (plates and text) - clarify regularization in plates and text is a collective effort of both @andiesilva and @diammarino 

- [ ] not capturing catch words - same as TCP 

- [ ] removed gaps where text was readable - counter to TCP 

- [ ] kept gap markup but supplied transcription when the text was faded - amended TCP dot inclusion

- [ ] kept TCP gap markup for when text could not be transcribed and added gaps when text not able to be transcribed on plates

- [ ] not capturing running heads - same as TCP

- [ ] plate transcription completed using two scans of the same copy at different states of degradation

- [ ] character declaration - pilcrow, tilde

# Text ReadingView w/ Marginalia

- [ ] XSLT transformation

# Woodcut Images ReadingView

- [ ] XSLT transformation

- [ ] implementation of JQuery

# Data Preservation

- [x] Create basic Prosopography file structure - persons and plate/plate section bibl

- [ ] Add descriptive information for Editors and project consultants in prosop. file

- [ ] Complete information entry for persons and plates/plate sections in prosop. file 

- [x] File Linking Spreadsheet

**Comment by andiesilva** [comment]
We need to check the header on TCP document so see why file is so slow to open
